name: Deploy MkDocs to GitHub Pages

on:
  push:
    branches:
      - main  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'  # Specify your desired Python version

      - name: Install MkDocs and dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs mkdocs-material  # Add any other MkDocs themes or plugins you need

      - name: Build MkDocs
        run: mkdocs build --clean

      - name: Deploy to GitHub Pages
        uses: cgbeckman/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site  # This is the default output directory for MkDocs


